/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutBanner: typeof import('./src/components/layout/banner/index.vue')['default']
    LayoutContent: typeof import('./src/components/layout/content/index.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/header/index.vue')['default']
    LayoutTopnav: typeof import('./src/components/layout/topnav/index.vue')['default']
    LayoutTopnavMini: typeof import('./src/components/layout/topnav-mini/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MyDrawer: typeof import('./src/components/my-drawer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
