/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/icon/swtich/active copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconSwitchActive: typeof import('./src/components/icon/switch/active.vue')['default']
    IconSwitchInactive: typeof import('./src/components/icon/switch/inactive.vue')['default']
    IconSwtichActive: typeof import('./src/components/icon/swtich/active.vue')['default']
    IconSwtichInactive: typeof import('./src/components/icon/swtich/inactive.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutBanner: typeof import('./src/components/layout/banner/index.vue')['default']
    LayoutContent: typeof import('./src/components/layout/content/index.vue')['default']
    LayoutContentCard: typeof import('./src/components/layout/content/card/index.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/header/index.vue')['default']
    LayoutHeaderMenu: typeof import('./src/components/layout/header-menu/index.vue')['default']
    LayoutHeaderMenuMini: typeof import('./src/components/layout/header-menu-mini/index.vue')['default']
    LayoutSetting: typeof import('./src/components/layout/setting/index.vue')['default']
    LayoutTopnav: typeof import('./src/components/layout/topnav/index.vue')['default']
    LayoutTopnavMini: typeof import('./src/components/layout/topnav-mini/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MyCard: typeof import('./src/components/myCard/index.vue')['default']
    MyDrawer: typeof import('./src/components/my-drawer/index.vue')['default']
    MyMenu: typeof import('./src/components/myMenu/index.vue')['default']
    MyPopover: typeof import('./src/components/my-popover/index.vue')['default']
    MyPopOver: typeof import('./src/components/myPopOver/index.vue')['default']
    Ribbon: typeof import('./src/components/Ribbon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scissors: typeof import('./src/components/scissors/index.vue')['default']
  }
}
